# Generated by Django 4.1 on 2022-08-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='text',
            new_name='message',
        ),
    ]
